### ISSUE TITLE
Can glitch out the head and tail of the picker

### ISSUE THREAD

**Issue by darthtroll** [veader/V8HorizontalPickerView#1]
To reproduce, go to the very last element and try and scroll a long distance and really fast as if you were expecting there to be another element after the last element. You'll notice that the view bugs out. With the indicator at 60px, it's only possible to mess up the tail of the horizontal picker, but if you moved the indicator to say, 120px, it becomes possible to bug out the head in addition to the tail. By bug out, I mean that it seems like a blank element is chosen after the last element, when you try and scroll back slowly, the last element is missing. Let me know if you need a better description.

**Comment by veader** [comment]
I just found this bug last night too while demoing the app I created this "control" for. I have a fix I'm going to push up shortly. Thanks for submitting a bug. 

What type of app are you using this for?

**Comment by veader** [comment]
Resolves bug where scrolling all elements off screen caused a blank element to be selected. Closed by bf63b9f1a05ea0b5a5d187f0a4572f74dc39f9a0

**Comment by darthtroll** [comment]
Hi veader,

Works great now! This is perfect for what I need. I was planning on using this for a restaurant-oriented app. I will be sure to tell you the name of the App when it's done. What inspired me to go out on google and find a horizontal picker is that I started off with a segmented control in a tool bar, and I quickly realized that it would pose as a problem because of the limited real estate.

Thanks :). Keep up the good work!

**Comment by darthtroll** [comment]
PS: It's my first App, and I am obsessed with getting the UI, efficiency and memory management right the first time and it's sort of a part-time hobby of mine, so it may be a few months before I have anything on the App Store :)

**Comment by veader** [comment]
The app that I built this for, (f/stats - http://fstatsapp.com), is now in the review queue. My  designer friend came up with the horizontal style date picker. (Which you could probably guess given the demo project uses dates as the example.)

I started with the UIPickerView and did the trick where you transform the picker view -90 degrees and then rotate the internal views +90 degrees. That works, but you can't remove the default styling on them in any easy way that I could find. That's when I started working on this custom control.

Glad it's working for you. I too do this on the side as a hobby and this is my second app. Let me know how it works for out for you.
