### ISSUE TITLE
Making V8HorizontalPicker Vertical?

### ISSUE THREAD

**Issue by micah-frank-studio** [veader/V8HorizontalPickerView#10]
I know that it completely contradicts the original purpose but I am wondering if there's a quick way to make V8HorizontalPicker vertical? I really like the look and feel of the horizontal one and I have related elements that need to be displayed vertically. Thanks for the great (and simple to implement) tool!

**Comment by veader** [comment]
@speedo I don't really have any plans at the moment to make the control work in the vertical configuration. You should be able to use the built in UIPickerView control or something similar depending on your needs.

If you wanted to take a dive into doing the proper logic to make it work vertically, I'd definitely take a look.

Cheers!
