### ISSUE TITLE
Tried to use this picker controller in my xib, data isn't showing up

### ISSUE THREAD

**Issue by zeropt7** [veader/V8HorizontalPickerView#12]
Hi, I've linked up the custom class of the V8HorinzontalPickerView in uiview in xib.
Data for items aren't showing up, when I scroll through the picker, the output console prints out "null".

I wonder what is the problem?

Thanks a lot.

**Comment by veader** [comment]
@zeropt7 can you send me a small sample project that demonstrates the problem?

My guess is that the delegate and data source might not be wired up properly in the XIB...

Please let me know.

**Comment by veader** [comment]
take a look at commits from issue #16 and the ib_test branch
