### ISSUE TITLE
Something like a Delegate method when the PickerViews are stopped

### ISSUE THREAD

**Issue by GustavoBraga** [veader/V8HorizontalPickerView#13]
First of all, thanks for sharing this code. Helped me a lot, and I'm having success in working with 3 v8HorizontalPickerViews at the same time. But now I need something like  "-scrollViewDidEndScrollingAnimation" delegate method. So I'll know when the Pickers are stopped to launch another viewController. I'm not so skilled in ios programming so I'm a little bit puzzled how could I implement something like that over your code.  If you have some idea or some thoughts about that to share it would be great. 

Thanks for helping

**Comment by veader** [comment]
@GustavoBraga I would do this by just tagging along with the horizontalPickerView:didSelectElementAtIndex: delegate callback. When that delegate is called, then fire off the launch of the ViewController.

Hopefully I'm understanding your problem correctly. Good luck.

(Closing this issue for now.)
