### ISSUE TITLE
Selection in the middle of the view.

### ISSUE THREAD

**Issue by MauriceZedde** [veader/V8HorizontalPickerView#18]
Hi, i like this pickerview but i want to change the selection to the middle of the view. Now it's more to the left. I tried to change this in the code but can't figure it out. Can anyone tell me how to change the selection to the middle of the view?

**Comment by veader** [comment]
@MauriceZedde have you tried playing with the selectionPoint and selectionIndicatorView?

https://github.com/veader/V8HorizontalPickerView/blob/master/V8HorizontalPickerView.h#L36

**Comment by MauriceZedde** [comment]
I played with V8HorizontalPickerView.m but i needed to set pickerView.selectionPoint = CGPointMake(120, 0); in the TestViewController.m
Thanks for your help :)

**Comment by veader** [comment]
Ideally you shouldn't need to change code in the .m unless you are doing major changes (which is encouraged). 

Glad it's working out for you.
Cheers!
