### ISSUE TITLE
Don't send didSelectElementAtIndex delegate callback when index is equal to previous index

### ISSUE THREAD

**Issue by rounak** [veader/V8HorizontalPickerView#21]
Can the picker not send delegate callbacks if the previous selected value is the same as the current selected value. This happens when I scroll the picker very lightly, and it returns to its original position.

**Comment by marckaraujo** [comment]
Yes, it is a problem, I´m trying to solve this atm

**Comment by veader** [comment]
Not sure we want to remove this behavior from the picker. You can pretty easily keep track of the last selected index in your delegate and choose to do nothing when you get the callback.
