### ISSUE TITLE
Select an item by default

### ISSUE THREAD

**Issue by ivangodfather** [veader/V8HorizontalPickerView#22]
Is there any way to set the selected item at a specific index?
For example, i fill an array with NSNumbers 1 to 100.
and i set:
self.agePickerView.selectedTextColor = [UIColor redColor];
[self.agePickerView setSelectedItemAtItem:50]  //Something like this
And then when the picker appears the item 50 of the datasource is marked as red.

**Comment by praagya-joshi** [comment]
To achieve this, you can use the method:

``` Objective-C
- (void)scrollToElement:(NSInteger)index animated:(BOOL)animate
```

If you want an element to be preselected, set animate to **NO**.

**Comment by veader** [comment]
Yup, we have a convenience method that praagya-joshi mentioned above:

https://github.com/veader/V8HorizontalPickerView/blob/master/V8HorizontalPickerView.h#L54
