### ISSUE TITLE
Landscape scrolling is messing up.

### ISSUE THREAD

**Issue by beloso** [veader/V8HorizontalPickerView#3]
When I have the horizontal picker in a View AND my view is in landscape orientation I can't seem to be able to scroll to the last element. Note that I can tap my desired element and it will scroll to that element nicely, what is not working properly is finger scrolling. 

Is there any special treatment I should be aware when the the horizontal picker is in landscape mode?

I have tried this on a picker with 2 and 3 elements. All elements are variable sized.

**Comment by veader** [comment]
Is this after an orientation change or was the app launched in landscape mode?

**Comment by beloso** [comment]
It happened when the view was loaded in landscape mode. I have added the:   

```
[self updateScrollContentInset];
```

to the layoutSubviews method as a temporary solution. If you could point me to a better solution I would appreciate it.

**Comment by veader** [comment]
Please try to use the most recent commit to see if it solves your problem. I've added the ability to change the orientation of the sample app and adjusted things within the control to properly save state. Let me know if this resolves any issues you might be having.
