### ISSUE TITLE
Performance issue with large amount of elements

### ISSUE THREAD

**Issue by fdgogogo** [veader/V8HorizontalPickerView#4]
If data source has a lot of elements, for example 1000 elements, the performance goes down significantly after about 200 elements, makes it impossible to make a circular picker (I'm trying to use a large array to produce a "fake" circular picker, which works fine in UIPickerView).

**Comment by edward-s** [comment]
it's easy to fix
in  V8HorizontalickerView.m
- (NSInteger)nearestElementToPoint:(CGPoint)point 

change 
for (int i = 0; i < numberOfElements; i++)
to
for (int i = currentSelectedIndex; i < numberOfElements; i++)
