### ISSUE TITLE
heavily refactored ARC version with several bug fixes

### ISSUE THREAD

**Issue by jmoody** [veader/V8HorizontalPickerView#6]
Hey Shawn,

Great job on this view.  I came across a few bugs and a couple of limitations.

In my project, I had a couple of requirements that were not met by this view:
1. must be able to share one delegate/data source between multiple picker views
2. needed (ok, wanted) an ARC version

I made a fork, which you can find here https://jmoody@github.com/jmoody/V8HorizontalPickerView.git

At the top of the README you can find some notes about what changes I made.  I am afraid that I walked all over your style and conventions.   For that, I am sorry because it won't be straight-forward to merge my changes and I broke backward compatibility by changing many many names.

Thanks for sharing your code!

jjm

**Comment by veader** [comment]
Wow, you have been busy! I saw your ARC changes a while back but didn't want to push the control to ARC yet as I still have 1-2 projects that are not ARC ready.

I'll have to dig through some of your other commits. I'd like to know what bugs you found and fixed but as you mentioned it's difficult to pull them out from all the other style changes. I'll keep digging.

Thanks!

**Comment by jmoody** [comment]
re: changes - yeah, sorry about all the style changes.  i was under some time constraints and need to quickly figure stuff out.  my usual technique when interfacing with a third-party library is to start ripping stuff apart so i can better understand what is going on.  9 times out of 10, i don't bother with a fork because the code is so terrible.  no so with your code; it was easy to understand and the scroll behavior is brilliant.

i don't have the code in front of me, but here is what i remember:

the biggest problem i had was that i could not share a delegate/data source between pickers.  this is because you are preloading data when the delegate or data source is set.  in my version the picker is always asking the the delegate and data source for the latest information.

you were not respecting the frame of the custom views.

there was a problem in the layout subviews where the selected-ness of a custom view was not set correctly, i think i left a note about this in code.

one thing that i did that i regret was i removed the element padding (?) - one of the properties that didn't seem to be used in any of the examples.  i wish that i had left it because i think it might be useful.

the ARC conversion was easy as pie.

keep bugging me for details.

**Comment by veader** [comment]
The delegate/data source issue I fixed in my latest commit. It was my ivars not being in the proper place. 

The delegate only asks for all the widths up front so it can calculate the width of the scroll view. The data should only requested as the views are drawn.

I'll be honest, I added the ability to do the views instead of the labels but I've never used it in a project. So I'll try to dissect what you have done to fix it and merge it back in.

The selected status never seems to be off for me. (Is this related to the issue with views instead of labels?)  I'll poke through your code and see if I can find what might be doing it. I do like some of your changes with setting the color of the labels with a selected state. 

Thanks for the complements. Always good to get feedback on your code. (And I know how looking at code makes you want to format it your way. My OCD is strong too... :) )

**Comment by jmoody** [comment]
_The delegate only asks for all the widths up front so it can calculate the width of the scroll view. The data should only requested as the views are drawn._  yeah, i am not entirely happy with the amount of times i ping the delegate/data source, but i don't know if it is a real problem as i haven't profiled that code yet.

_The selected status never seems to be off for me. (Is this related to the issue with views instead of labels?)_  ==> yes.

```
- (V8HorizontalPickerLabel *)labelForForElementAtIndex:(NSInteger)index withTitle:(NSString *)title {
    CGRect labelFrame     = [self frameForElementAtIndex:index];
    V8HorizontalPickerLabel *elementLabel = [[V8HorizontalPickerLabel alloc] initWithFrame:labelFrame];

    elementLabel.textAlignment   = UITextAlignmentCenter;
    elementLabel.backgroundColor = self.backgroundColor;
    elementLabel.text            = title;
    elementLabel.font            = self.elementFont;

    elementLabel.normalStateColor   = self.textColor;
    elementLabel.selectedStateColor = self.selectedTextColor;

    // show selected status if this element is the selected one and is currently over selectionPoint
    int currentIndex = [self nearestElementToCenter];
    elementLabel.selectedElement = (currentSelectedIndex == index) && (currentIndex == currentSelectedIndex);

    return [elementLabel autorelease];
}
```

you are setting the selected-ness of the label in this method, which is all well and good, but if you use a V8HorizontalPickerView, the selected-ness  is _not_ set in the first pass through layout subviews, ie - when the view is first shown the cell under the selection indicator is _not_ highlighted/selected.  you could argue that the delegate should handle this, but it seems like the picker should figure it out.
