### ISSUE TITLE
Multiple HorizontalPickers Merging Datasource/Delegate

### ISSUE THREAD

**Issue by rnystrom** [veader/V8HorizontalPickerView#8]
I'm trying to use 5 of these sliders at the same time, but I can't for the life of me separate the data. I used your demo and it will **not** work with 2 sliders in one view. Do you have any idea why? I tried going through the source but figured it's more work than worth it at the moment. I really like what you're after, but this _should_ be able to work with more than one slider.

And if I'm wrong, I'd love to see an example with two sliders so I can figure out what I'm doing wrong here.

Thanks!

**Comment by veader** [comment]
I found a bug that was likely the cause of this. I've also pushed up a branch that has an example with two pickers at once. Let me know if this doesn't answer the question for you. Thanks for checking out the control.

**Comment by rnystrom** [comment]
Awesome thanks! I'll check it out

---

Ryan Nystrom
Web & iOS Development
rnystrom@whoisryannystrom.com
http://whoisryannystrom.com
937.367.8939
